'use strict';

let config = {
  'WEAPON_ADVANCEDRIFLE': {
    name: 'Advanced Rifle',
    bone: 24818,
    ammo: 'AMMO_RIFLE',
    category: 'Assault',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_ar_advancedrifle',
  },
  'WEAPON_ASSAULTRIFLE': {
    name: 'Assault Rifle',
    bone: 24818,
    ammo: 'AMMO_RIFLE',
    category: 'Assault',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_ar_assaultrifle',
  },
  'WEAPON_BULLPUPRIFLE': {
    name: 'Bullpup Rifle',
    bone: 24818,
    ammo: 'AMMO_RIFLE',
    category: 'Assault',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_ar_bullpuprifle',
  },
  'WEAPON_CARBINERIFLE': {
    name: 'Carbine Rifle',
    bone: 24818,
    ammo: 'AMMO_RIFLE',
    category: 'Assault',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_ar_carbinerifle',
  },
  'WEAPON_COMPACTRIFLE': {
    name: 'Compact Rifle',
    bone: 24818,
    ammo: 'AMMO_RIFLE',
    category: 'Assault',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_ar_compactrifle',
  },
  'WEAPON_SPECIALCARBINE': {
    name: 'Special Carbine',
    bone: 24818,
    ammo: 'AMMO_RIFLE',
    category: 'Assault',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_ar_specialcarbine',
  },
  'WEAPON_BZGAS': {
    name: 'BZ Gas',
    bone: 24818,
    category: 'Thrown',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_ex_grenadesmoke',
  },
  'WEAPON_BALL': {
    name: 'Ball',
    bone: 24818,
    category: 'Thrown',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_am_baseball',
  },
  'WEAPON_FIREEXTINGUISHER': {
    name: 'Fire Extinguisher',
    bone: 24818,
    category: 'Thrown',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_am_fire_exting',
  },
  'WEAPON_SNOWBALL': {
    name: 'Snow Ball',
    bone: 24818,
    category: 'Thrown',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_ex_snowball',
  },
  'WEAPON_STICKYBOMB': {
    name: 'Sticky Bomb',
    bone: 24818,
    category: 'Thrown',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'prop_bomb_01_s',
  },
  'WEAPON_SMOKEGRENADE': {
    name: 'Smoke Grenade',
    bone: 24818,
    category: 'Thrown',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_ex_grenadesmoke',
  },
  'WEAPON_PROXMINE': {
    name: 'Prox Mine',
    bone: 24818,
    category: 'Thrown',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_ex_apmine',
  },
  'WEAPON_PETROLCAN': {
    name: 'Petrol Can',
    bone: 24818,
    category: 'Thrown',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_am_jerrycan',
  },
  'WEAPON_MOLOTOV': {
    name: 'Molotov',
    bone: 24818,
    category: 'Thrown',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_ex_molotov',
  },
  'WEAPON_GRENADE': {
    name: 'Grenade',
    bone: 24818,
    category: 'Thrown',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_ex_grenadefrag',
  },
  'WEAPON_APPISTOL': {
    name: 'AP Pistol',
    bone: 51826,
    ammo: 'AMMO_PISTOL',
    category: 'Handgun',
    position: new mp.Vector3(-0.01, 0.10, 0.07),
    rotation: new mp.Vector3(-115.0, 0.0, 0.0),
    model: 'w_pi_appistol',
  },
  'WEAPON_VINTAGEPISTOL': {
    name: 'Vintage Pistol',
    bone: 51826,
    ammo: 'AMMO_PISTOL',
    category: 'Handgun',
    position: new mp.Vector3(-0.01, 0.10, 0.07),
    rotation: new mp.Vector3(-115.0, 0.0, 0.0),
    model: 'w_pi_vintage_pistol',
  },
  'WEAPON_HEAVYPISTOL': {
    name: 'Heavy Pistol',
    bone: 51826,
    ammo: 'AMMO_PISTOL',
    category: 'Handgun',
    position: new mp.Vector3(-0.01, 0.10, 0.07),
    rotation: new mp.Vector3(-115.0, 0.0, 0.0),
    model: 'w_pi_heavypistol',
  },
  'WEAPON_SNSPISTOL': {
    name: 'SNS Pistol',
    bone: 58271,
    ammo: 'AMMO_PISTOL',
    category: 'Handgun',
    position: new mp.Vector3(-0.01, 0.1, -0.07),
    rotation: new mp.Vector3(-55.0, 0.10, 0.0),
    model: 'w_pi_sns_pistol',
  },
  'WEAPON_STUNGUN': {
    name: 'Stungun',
    bone: 58271,
    ammo: 'AMMO_STUNGUN',
    category: 'Handgun',
    position: new mp.Vector3(-0.01, 0.1, -0.07),
    rotation: new mp.Vector3(-55.0, 0.10, 0.0),
    model: 'w_pi_stungun',
  },
  'WEAPON_REVOLVER': {
    name: 'Revolver',
    bone: 58271,
    ammo: 'AMMO_PISTOL',
    category: 'Handgun',
    position: new mp.Vector3(-0.01, 0.1, -0.07),
    rotation: new mp.Vector3(-55.0, 0.10, 0.0),
    model: 'w_pi_revolver',
  },
  'WEAPON_PISTOL50': {
    name: '.50 Pistol',
    bone: 51826,
    ammo: 'AMMO_PISTOL',
    category: 'Handgun',
    position: new mp.Vector3(-0.01, 0.10, 0.07),
    rotation: new mp.Vector3(-115.0, 0.0, 0.0),
    model: 'w_pi_pistol50',
  },
  'WEAPON_PISTOL': {
    name: 'Pistol',
    bone: 51826,
    ammo: 'AMMO_PISTOL',
    category: 'Handgun',
    position: new mp.Vector3(-0.01, 0.10, 0.07),
    rotation: new mp.Vector3(-115.0, 0.0, 0.0),
    model: 'w_pi_pistol',
  },
  'WEAPON_MARKSMANPISTOL': {
    name: 'Marksman Pistol',
    bone: 58271,
    ammo: 'AMMO_PISTOL',
    category: 'Handgun',
    position: new mp.Vector3(-0.01, 0.1, -0.07),
    rotation: new mp.Vector3(-55.0, 0.10, 0.0),
    model: 'w_pi_marksmanpistol',
  },
  'WEAPON_FLAREGUN': {
    name: 'Flare Gun',
    bone: 58271,
    ammo: 'AMMO_FLARE',
    category: 'Handgun',
    position: new mp.Vector3(-0.01, 0.1, -0.07),
    rotation: new mp.Vector3(-55.0, 0.10, 0.0),
    model: 'w_pi_flaregun',
  },
  'WEAPON_COMBATPISTOL': {
    name: 'Combat Pistol',
    bone: 51826,
    ammo: 'AMMO_PISTOL',
    category: 'Handgun',
    position: new mp.Vector3(-0.01, 0.10, 0.07),
    rotation: new mp.Vector3(-115.0, 0.0, 0.0),
    model: 'w_pi_combatpistol',
  },
  'WEAPON_ASSAULTSHOTGUN': {
    name: 'Assault Shotgun',
    bone: 24818,
    ammo: 'AMMO_SHOTGUN',
    category: 'Shotgun',
    position: new mp.Vector3(0.1, -0.15, 0.0),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_sg_assaultshotgun',
  },
  'WEAPON_MUSKET': {
    name: 'Musket',
    bone: 24818,
    ammo: 'AMMO_SHOTGUN',
    category: 'Shotgun',
    position: new mp.Vector3(0.1, -0.15, 0.0),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_ar_musket',
  },
  'WEAPON_DBSHOTGUN': {
    name: 'Double Barrel Shotgun',
    bone: 24818,
    ammo: 'AMMO_SHOTGUN',
    category: 'Shotgun',
    position: new mp.Vector3(0.1, -0.15, 0.0),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_sg_dbshotgun',
  },
  'WEAPON_PUMPSHOTGUN': {
    name: 'Pump Shotgun',
    bone: 24818,
    ammo: 'AMMO_SHOTGUN',
    category: 'Shotgun',
    position: new mp.Vector3(0.1, -0.15, 0.0),
    rotation: new mp.Vector3(0.0, 135.0, 0.0),
    model: 'w_sg_pumpshotgun',
  },
  'WEAPON_SAWNOFFSHOTGUN': {
    name: 'Sawn-off Shotgun',
    bone: 24818,
    ammo: 'AMMO_SHOTGUN',
    category: 'Shotgun',
    position: new mp.Vector3(0.1, -0.15, 0.0),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_sg_sawnoff',
  },
  'WEAPON_HEAVYSHOTGUN': {
    name: 'Heavy Shotgun',
    bone: 24818,
    ammo: 'AMMO_SHOTGUN',
    category: 'Shotgun',
    position: new mp.Vector3(0.1, -0.15, 0.0),
    rotation: new mp.Vector3(0.0, 225.0, 0.0),
    model: 'w_sg_heavyshotgun',
  },
  'WEAPON_BULLPUPSHOTGUN': {
    name: 'Bullpup Shotgun',
    bone: 24818,
    ammo: 'AMMO_SHOTGUN',
    category: 'Shotgun',
    position: new mp.Vector3(0.1, -0.15, 0.0),
    rotation: new mp.Vector3(0.0, 135.0, 0.0),
    model: 'w_sg_bullpupshotgun',
  },
  'WEAPON_AUTOSHOTGUN': {
    name: 'Auto Shotgun',
    bone: 24818,
    ammo: 'AMMO_SHOTGUN',
    category: 'Shotgun',
    position: new mp.Vector3(0.1, 0.15, 0.0),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_sg_autoshotgun',
  },
  'WEAPON_ASSAULTSMG': {
    name: 'Assault SMG',
    bone: 24818,
    ammo: 'AMMO_SMG',
    category: 'Machine',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_sb_assaultsmg',
  },
  'WEAPON_MINISMG': {
    name: 'Mini SMG',
    bone: 24818,
    ammo: 'AMMO_SMG',
    category: 'Machine',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_sb_minismg',
  },
  'WEAPON_GUSENBERG': {
    name: 'Gusenberg',
    bone: 24818,
    ammo: 'AMMO_MG',
    category: 'Machine',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_sb_gusenberg',
  },
  'WEAPON_SMG': {
    name: 'SMG',
    bone: 24818,
    ammo: 'AMMO_SMG',
    category: 'Machine',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_sb_smg',
  },
  'WEAPON_MG': {
    name: 'MG',
    bone: 24818,
    ammo: 'AMMO_MG',
    category: 'Machine',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_mg_mg',
  },
  'WEAPON_MICROSMG': {
    name: 'Micro SMG',
    bone: 24818,
    ammo: 'AMMO_SMG',
    category: 'Machine',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_sb_microsmg',
  },
  'WEAPON_MACHINEPISTOL': {
    name: 'Machine Pistol',
    bone: 24818,
    ammo: 'AMMO_PISTOL',
    category: 'Machine',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_sb_machinepistol',
  },
  'WEAPON_COMBATMG': {
    name: 'Combat MG',
    bone: 24818,
    ammo: 'AMMO_MG',
    category: 'Machine',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_mg_combatmg',
  },
  'WEAPON_COMBATPDW': {
    name: 'Combat PDW',
    bone: 24818,
    ammo: 'AMMO_MG',
    category: 'Machine',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_mg_combatpdw',
  },
  'WEAPON_BAT': {
    name: 'Bat',
    bone: 24818,
    category: 'Melee',
    position: new mp.Vector3(0.0, 0.0, 0.0),
    rotation: new mp.Vector3(320.0, 320.0, 320.0),
    model: 'w_me_bat',
  },
  'WEAPON_FLASHLIGHT': {
    name: 'Flashlight',
    bone: 24818,
    category: 'Melee',
    position: new mp.Vector3(0.0, 0.0, 0.0),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'prop_tool_torch',
  },
  'WEAPON_GOLFCLUB': {
    name: 'Golfclub',
    bone: 24818,
    category: 'Melee',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_me_gclub',
  },
  'WEAPON_HAMMER': {
    name: 'Hammer',
    bone: 24818,
    category: 'Melee',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'prop_tool_hammer',
  },
  'WEAPON_HATCHET': {
    name: 'Hatchet',
    bone: 24818,
    category: 'Melee',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_me_hatchet',
  },
  'WEAPON_BOTTLE': {
    name: 'Broken Bottle',
    bone: 24818,
    category: 'Melee',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'prop_w_me_bottle',
  },
  'WEAPON_CROWBAR': {
    name: 'Crowbar',
    bone: 24818,
    category: 'Melee',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_me_crowbar',
  },
  'WEAPON_KNIFE': {
    name: 'Knife',
    bone: 24818,
    category: 'Melee',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'prop_w_me_knife_01',
  },
  'WEAPON_KNUCKLE': {
    name: 'Knuckle',
    bone: 24818,
    category: 'Melee',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_me_knuckle',
  },
  'WEAPON_MACHETE': {
    name: 'Machete',
    bone: 24818,
    category: 'Melee',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'prop_ld_w_me_machette',
  },
  'WEAPON_SWITCHBLADE': {
    name: 'Switchblade',
    bone: 24818,
    category: 'Melee',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'prop_w_me_switchblade',
  },
  'WEAPON_NIGHTSTICK': {
    name: 'Nightstick',
    bone: 24818,
    category: 'Melee',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_me_nightstick',
  },
  'WEAPON_WRENCH': {
    name: 'Wrench',
    bone: 24818,
    category: 'Other',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'prop_cs_wrench',
  },
  'WEAPON_PIPEBOMB': {
    name: 'Pipe Bomb',
    bone: 24818,
    category: 'Other',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'prop_bomb_01',
  },
  'WEAPON_POOLCUE': {
    name: 'Pool Cue',
    bone: 24818,
    category: 'Other',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'prop_pool_cue',
  },
  'WEAPON_HANDCUFFS': {
    name: 'Handcuffs',
    bone: 24818,
    category: 'Other',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'prop_cs_cuffs_01',
  },
  'WEAPON_GARBAGEBAG': {
    name: 'Garbage Bag',
    bone: 24818,
    category: 'Other',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'prop_ld_rub_binbag_01',
  },
  'WEAPON_DIGISCANNER': {
    name: 'Digi Scanner',
    bone: 24818,
    category: 'Other',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_am_digiscanner',
  },
  'WEAPON_BATTLEAXE': {
    name: 'Battle Axe',
    bone: 24818,
    category: 'Other',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'prop_tool_fireaxe',
  },
  'WEAPON_DAGGER': {
    name: 'Dagger',
    bone: 24818,
    category: 'Other',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'prop_w_me_dagger',
  },
  'WEAPON_REMOTESNIPER': {
    name: 'Remote Sniper',
    bone: 24818,
    ammo: 'AMMO_SNIPER',
    category: 'Other',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: '',
  },
  'WEAPON_STINGER': {
    name: 'Stinger',
    bone: 24818,
    ammo: 'AMMO_STINGER',
    category: 'Other',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: '',
  },
  'WEAPON_HEAVYSNIPER': {
    name: 'Heavy Sniper',
    bone: 24818,
    ammo: 'AMMO_SNIPER',
    category: 'Sniper',
    position: new mp.Vector3(0.1, -0.15, 0.0),
    rotation: new mp.Vector3(0.0, 135.0, 0.0),
    model: 'w_sr_heavysniper',
  },
  'WEAPON_MARKSMANRIFLE': {
    name: 'Marksman Rifle',
    bone: 24818,
    ammo: 'AMMO_SNIPER',
    category: 'Sniper',
    position: new mp.Vector3(0.1, -0.15, 0.0),
    rotation: new mp.Vector3(0.0, 135.0, 0.0),
    model: 'w_sr_marksmanrifle',
  },
  'WEAPON_SNIPERRIFLE': {
    name: 'Sniper Rifle',
    bone: 24818,
    ammo: 'AMMO_SNIPER',
    category: 'Sniper',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_sr_sniperrifle',
  },
  'WEAPON_RPG': {
    name: 'RPG',
    bone: 24818,
    ammo: 'AMMO_RPG',
    category: 'Heavy',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_lr_rpg',
  },
  'WEAPON_COMPACTLAUNCHER': {
    name: 'Compact Launcher',
    bone: 24818,
    ammo: ['AMMO_GRENADELAUNCHER', 'AMMO_GRENADELAUNCHER_SMOKE'],
    category: 'Heavy',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: '',
  },
  'WEAPON_FIREWORK': {
    name: 'Firework',
    bone: 24818,
    ammo: 'AMMO_FIREWORK',
    category: 'Heavy',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_lr_firework',
  },
  'WEAPON_GRENADELAUNCHER': {
    name: 'Grenade Launcher',
    bone: 24818,
    ammo: ['AMMO_GRENADELAUNCHER', 'AMMO_GRENADELAUNCHER_SMOKE'],
    category: 'Heavy',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_lr_grenadelauncher',
  },
  'WEAPON_HOMINGLAUNCHER': {
    name: 'Homing Launcher',
    bone: 24818,
    ammo: 'AMMO_ROCKETLAUNCHER',
    category: 'Heavy',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_lr_homing',
  },
  'WEAPON_MINIGUN': {
    name: 'Minigun',
    bone: 24818,
    ammo: 'AMMO_MINIGUN',
    category: 'Heavy',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_mg_minigun',
  },
  'WEAPON_RAILGUN': {
    name: 'Rail Gun',
    bone: 24818,
    ammo: 'AMMO_RAILGUN',
    category: 'Heavy',
    position: new mp.Vector3(0.0, 0.0, 0.0 ),
    rotation: new mp.Vector3(0.0, 0.0, 0.0),
    model: 'w_ar_railgun',
  },
};

module.exports = config;
