exports.UTILS = require('./YARP/exports/utils.js');
require('./YARP/modules/base.js');
require('./YARP/modules/browser.js');
require('./YARP/modules/characters.js');
require('./YARP/modules/commands.js');
require('./YARP/modules/menus.js');
require('./YARP/modules/ipls.js');
require('./YARP/modules/inventory.js');
require('./YARP/modules/weapons.js');
require('./YARP/modules/bank.js');
